import os
import json
from PIL import Image, ImageOps

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHOTOS_DIR = os.path.join(BASE_DIR, "public", "images", "photos")
THUMBS_DIR = os.path.join(BASE_DIR, "public", "images", "photos_thumbs")
JSON_OUTPUT = os.path.join(BASE_DIR, "public", "content", "photos.json")
TS_OUTPUT = os.path.join(BASE_DIR, "src", "data", "photosData.ts")

os.makedirs(THUMBS_DIR, exist_ok=True)
os.makedirs(os.path.dirname(JSON_OUTPUT), exist_ok=True)
os.makedirs(os.path.dirname(TS_OUTPUT), exist_ok=True)

VALID_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp"}

files = sorted(
    [
        f for f in os.listdir(PHOTOS_DIR)
        if os.path.isfile(os.path.join(PHOTOS_DIR, f))
        and os.path.splitext(f)[1].lower() in VALID_EXTENSIONS
        and not f.startswith(".")
    ]
)

print(f"Processing {len(files)} photos from {PHOTOS_DIR}...")

photos_data = []

for idx, filename in enumerate(files, start=1):
    src_path = os.path.join(PHOTOS_DIR, filename)
    name_root, _ = os.path.splitext(filename)
    thumb_filename = f"{name_root}.webp"
    thumb_path = os.path.join(THUMBS_DIR, thumb_filename)

    width = 0
    height = 0

    try:
        with Image.open(src_path) as img:
            img = ImageOps.exif_transpose(img)
            width, height = img.size

            # Create thumbnail if not exists or if source is newer
            if not os.path.exists(thumb_path) or os.path.getmtime(src_path) > os.path.getmtime(thumb_path):
                thumb_img = img.copy()
                thumb_img.thumbnail((700, 700), Image.Resampling.LANCZOS)
                if thumb_img.mode in ("RGBA", "P"):
                    thumb_img = thumb_img.convert("RGB")
                thumb_img.save(thumb_path, "WEBP", quality=82, method=4)

        aspect_ratio = round(width / height, 4) if height > 0 else 1.3333

        # URL-safe encoding for filenames with spaces
        # Vite serves files in public/ at the root path:
        # e.g., /images/photos/<filename> and /images/photos_thumbs/<thumb_filename>
        src_url = f"/images/photos/{filename}"
        thumb_url = f"/images/photos_thumbs/{thumb_filename}"

        photos_data.append({
            "id": idx,
            "filename": filename,
            "src": src_url,
            "thumb": thumb_url,
            "width": width,
            "height": height,
            "aspectRatio": aspect_ratio
        })
    except Exception as e:
        print(f"Error processing {filename}: {e}")

# Save JSON
with open(JSON_OUTPUT, "w", encoding="utf-8") as f:
    json.dump(photos_data, f, indent=2)
print(f"Saved {len(photos_data)} photos to {JSON_OUTPUT}")

# Save TypeScript file for instant imports
ts_content = f"""// Auto-generated by scripts/prepare_photos.py
export interface WorkshopPhoto {{
  id: number;
  filename: string;
  src: string;
  thumb: string;
  width: number;
  height: number;
  aspectRatio: number;
}}

export const workshopPhotos: WorkshopPhoto[] = {json.dumps(photos_data, indent=2)};
"""

with open(TS_OUTPUT, "w", encoding="utf-8") as f:
    f.write(ts_content)
print(f"Saved TypeScript data to {TS_OUTPUT}")
