// Auto-generated by scripts/prepare_photos.py
export interface WorkshopPhoto {
  id: number;
  filename: string;
  src: string;
  thumb: string;
  width: number;
  height: number;
  aspectRatio: number;
}

export const workshopPhotos: WorkshopPhoto[] = [
  {
    "id": 1,
    "filename": "4e2a23b7-0eca-42b6-96d2-948cede1bd5b 2.JPG",
    "src": "/images/photos/4e2a23b7-0eca-42b6-96d2-948cede1bd5b 2.JPG",
    "thumb": "/images/photos_thumbs/4e2a23b7-0eca-42b6-96d2-948cede1bd5b 2.webp",
    "width": 1204,
    "height": 1600,
    "aspectRatio": 0.7525
  },
  {
    "id": 2,
    "filename": "5592b086-2d5c-47b2-b1c4-651930014dd7 2.jpg",
    "src": "/images/photos/5592b086-2d5c-47b2-b1c4-651930014dd7 2.jpg",
    "thumb": "/images/photos_thumbs/5592b086-2d5c-47b2-b1c4-651930014dd7 2.webp",
    "width": 3072,
    "height": 4080,
    "aspectRatio": 0.7529
  },
  {
    "id": 3,
    "filename": "910657f9-69d6-4664-ac63-acf233fa3774 2.JPG",
    "src": "/images/photos/910657f9-69d6-4664-ac63-acf233fa3774 2.JPG",
    "thumb": "/images/photos_thumbs/910657f9-69d6-4664-ac63-acf233fa3774 2.webp",
    "width": 3072,
    "height": 4080,
    "aspectRatio": 0.7529
  },
  {
    "id": 4,
    "filename": "IMG_0003.png",
    "src": "/images/photos/IMG_0003.png",
    "thumb": "/images/photos_thumbs/IMG_0003.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 5,
    "filename": "IMG_0004.png",
    "src": "/images/photos/IMG_0004.png",
    "thumb": "/images/photos_thumbs/IMG_0004.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 6,
    "filename": "IMG_0005.png",
    "src": "/images/photos/IMG_0005.png",
    "thumb": "/images/photos_thumbs/IMG_0005.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 7,
    "filename": "IMG_0006.png",
    "src": "/images/photos/IMG_0006.png",
    "thumb": "/images/photos_thumbs/IMG_0006.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 8,
    "filename": "IMG_0007.png",
    "src": "/images/photos/IMG_0007.png",
    "thumb": "/images/photos_thumbs/IMG_0007.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 9,
    "filename": "IMG_0008.png",
    "src": "/images/photos/IMG_0008.png",
    "thumb": "/images/photos_thumbs/IMG_0008.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 10,
    "filename": "IMG_0009.png",
    "src": "/images/photos/IMG_0009.png",
    "thumb": "/images/photos_thumbs/IMG_0009.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 11,
    "filename": "IMG_0010.png",
    "src": "/images/photos/IMG_0010.png",
    "thumb": "/images/photos_thumbs/IMG_0010.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 12,
    "filename": "IMG_0011.png",
    "src": "/images/photos/IMG_0011.png",
    "thumb": "/images/photos_thumbs/IMG_0011.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 13,
    "filename": "IMG_0012.png",
    "src": "/images/photos/IMG_0012.png",
    "thumb": "/images/photos_thumbs/IMG_0012.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 14,
    "filename": "IMG_0013.png",
    "src": "/images/photos/IMG_0013.png",
    "thumb": "/images/photos_thumbs/IMG_0013.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 15,
    "filename": "IMG_0014.png",
    "src": "/images/photos/IMG_0014.png",
    "thumb": "/images/photos_thumbs/IMG_0014.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 16,
    "filename": "IMG_0015.png",
    "src": "/images/photos/IMG_0015.png",
    "thumb": "/images/photos_thumbs/IMG_0015.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 17,
    "filename": "IMG_0016.png",
    "src": "/images/photos/IMG_0016.png",
    "thumb": "/images/photos_thumbs/IMG_0016.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 18,
    "filename": "IMG_0017.png",
    "src": "/images/photos/IMG_0017.png",
    "thumb": "/images/photos_thumbs/IMG_0017.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 19,
    "filename": "IMG_0018.png",
    "src": "/images/photos/IMG_0018.png",
    "thumb": "/images/photos_thumbs/IMG_0018.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 20,
    "filename": "IMG_0019.png",
    "src": "/images/photos/IMG_0019.png",
    "thumb": "/images/photos_thumbs/IMG_0019.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 21,
    "filename": "IMG_0020.png",
    "src": "/images/photos/IMG_0020.png",
    "thumb": "/images/photos_thumbs/IMG_0020.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 22,
    "filename": "IMG_0021.png",
    "src": "/images/photos/IMG_0021.png",
    "thumb": "/images/photos_thumbs/IMG_0021.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 23,
    "filename": "IMG_0022.png",
    "src": "/images/photos/IMG_0022.png",
    "thumb": "/images/photos_thumbs/IMG_0022.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 24,
    "filename": "IMG_0023.png",
    "src": "/images/photos/IMG_0023.png",
    "thumb": "/images/photos_thumbs/IMG_0023.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 25,
    "filename": "IMG_0024.png",
    "src": "/images/photos/IMG_0024.png",
    "thumb": "/images/photos_thumbs/IMG_0024.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 26,
    "filename": "IMG_0025.png",
    "src": "/images/photos/IMG_0025.png",
    "thumb": "/images/photos_thumbs/IMG_0025.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 27,
    "filename": "IMG_0026.png",
    "src": "/images/photos/IMG_0026.png",
    "thumb": "/images/photos_thumbs/IMG_0026.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 28,
    "filename": "IMG_0027.png",
    "src": "/images/photos/IMG_0027.png",
    "thumb": "/images/photos_thumbs/IMG_0027.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 29,
    "filename": "IMG_0028.png",
    "src": "/images/photos/IMG_0028.png",
    "thumb": "/images/photos_thumbs/IMG_0028.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 30,
    "filename": "IMG_0029.png",
    "src": "/images/photos/IMG_0029.png",
    "thumb": "/images/photos_thumbs/IMG_0029.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 31,
    "filename": "IMG_0030.png",
    "src": "/images/photos/IMG_0030.png",
    "thumb": "/images/photos_thumbs/IMG_0030.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 32,
    "filename": "IMG_0031.png",
    "src": "/images/photos/IMG_0031.png",
    "thumb": "/images/photos_thumbs/IMG_0031.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 33,
    "filename": "IMG_0032.png",
    "src": "/images/photos/IMG_0032.png",
    "thumb": "/images/photos_thumbs/IMG_0032.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 34,
    "filename": "IMG_0033.png",
    "src": "/images/photos/IMG_0033.png",
    "thumb": "/images/photos_thumbs/IMG_0033.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 35,
    "filename": "IMG_0034.png",
    "src": "/images/photos/IMG_0034.png",
    "thumb": "/images/photos_thumbs/IMG_0034.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 36,
    "filename": "IMG_0035.png",
    "src": "/images/photos/IMG_0035.png",
    "thumb": "/images/photos_thumbs/IMG_0035.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 37,
    "filename": "IMG_0036.png",
    "src": "/images/photos/IMG_0036.png",
    "thumb": "/images/photos_thumbs/IMG_0036.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 38,
    "filename": "IMG_0037.png",
    "src": "/images/photos/IMG_0037.png",
    "thumb": "/images/photos_thumbs/IMG_0037.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 39,
    "filename": "IMG_0038.png",
    "src": "/images/photos/IMG_0038.png",
    "thumb": "/images/photos_thumbs/IMG_0038.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 40,
    "filename": "IMG_0039.png",
    "src": "/images/photos/IMG_0039.png",
    "thumb": "/images/photos_thumbs/IMG_0039.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 41,
    "filename": "IMG_0040.png",
    "src": "/images/photos/IMG_0040.png",
    "thumb": "/images/photos_thumbs/IMG_0040.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 42,
    "filename": "IMG_0041.png",
    "src": "/images/photos/IMG_0041.png",
    "thumb": "/images/photos_thumbs/IMG_0041.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 43,
    "filename": "IMG_4516 2.JPG",
    "src": "/images/photos/IMG_4516 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4516 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 44,
    "filename": "IMG_4517 2.JPG",
    "src": "/images/photos/IMG_4517 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4517 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 45,
    "filename": "IMG_4518 2.JPG",
    "src": "/images/photos/IMG_4518 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4518 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 46,
    "filename": "IMG_4519 2.JPG",
    "src": "/images/photos/IMG_4519 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4519 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 47,
    "filename": "IMG_4520 2.JPG",
    "src": "/images/photos/IMG_4520 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4520 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 48,
    "filename": "IMG_4521 2.JPG",
    "src": "/images/photos/IMG_4521 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4521 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 49,
    "filename": "IMG_4522 2.JPG",
    "src": "/images/photos/IMG_4522 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4522 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 50,
    "filename": "IMG_4523 2.JPG",
    "src": "/images/photos/IMG_4523 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4523 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 51,
    "filename": "IMG_4524 2.JPG",
    "src": "/images/photos/IMG_4524 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4524 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 52,
    "filename": "IMG_4529 2.JPG",
    "src": "/images/photos/IMG_4529 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4529 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 53,
    "filename": "IMG_4530 2.JPG",
    "src": "/images/photos/IMG_4530 2.JPG",
    "thumb": "/images/photos_thumbs/IMG_4530 2.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 54,
    "filename": "IMG_8343.jpeg",
    "src": "/images/photos/IMG_8343.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8343.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 55,
    "filename": "IMG_8347.jpeg",
    "src": "/images/photos/IMG_8347.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8347.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 56,
    "filename": "IMG_8348.jpeg",
    "src": "/images/photos/IMG_8348.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8348.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 57,
    "filename": "IMG_8349.jpeg",
    "src": "/images/photos/IMG_8349.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8349.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 58,
    "filename": "IMG_8350.jpeg",
    "src": "/images/photos/IMG_8350.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8350.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 59,
    "filename": "IMG_8351.jpeg",
    "src": "/images/photos/IMG_8351.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8351.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 60,
    "filename": "IMG_8352.jpeg",
    "src": "/images/photos/IMG_8352.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8352.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 61,
    "filename": "IMG_8354.jpeg",
    "src": "/images/photos/IMG_8354.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8354.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 62,
    "filename": "IMG_8355.jpeg",
    "src": "/images/photos/IMG_8355.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8355.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 63,
    "filename": "IMG_8357.jpeg",
    "src": "/images/photos/IMG_8357.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8357.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 64,
    "filename": "IMG_8358.jpeg",
    "src": "/images/photos/IMG_8358.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8358.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 65,
    "filename": "IMG_8362.jpeg",
    "src": "/images/photos/IMG_8362.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8362.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 66,
    "filename": "IMG_8363.jpeg",
    "src": "/images/photos/IMG_8363.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8363.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 67,
    "filename": "IMG_8364.jpeg",
    "src": "/images/photos/IMG_8364.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8364.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 68,
    "filename": "IMG_8365.jpeg",
    "src": "/images/photos/IMG_8365.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8365.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 69,
    "filename": "IMG_8366.jpeg",
    "src": "/images/photos/IMG_8366.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8366.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 70,
    "filename": "IMG_8370.jpeg",
    "src": "/images/photos/IMG_8370.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8370.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 71,
    "filename": "IMG_8371.jpeg",
    "src": "/images/photos/IMG_8371.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8371.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 72,
    "filename": "IMG_8372.jpeg",
    "src": "/images/photos/IMG_8372.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8372.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 73,
    "filename": "IMG_8373.jpeg",
    "src": "/images/photos/IMG_8373.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8373.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 74,
    "filename": "IMG_8375.jpeg",
    "src": "/images/photos/IMG_8375.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8375.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 75,
    "filename": "IMG_8376.jpeg",
    "src": "/images/photos/IMG_8376.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8376.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 76,
    "filename": "IMG_8377.jpeg",
    "src": "/images/photos/IMG_8377.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8377.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 77,
    "filename": "IMG_8378.jpeg",
    "src": "/images/photos/IMG_8378.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8378.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 78,
    "filename": "IMG_8381.jpeg",
    "src": "/images/photos/IMG_8381.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8381.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 79,
    "filename": "IMG_8382.jpeg",
    "src": "/images/photos/IMG_8382.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8382.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 80,
    "filename": "IMG_8383.jpeg",
    "src": "/images/photos/IMG_8383.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8383.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 81,
    "filename": "IMG_8384.jpeg",
    "src": "/images/photos/IMG_8384.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8384.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 82,
    "filename": "IMG_8385.jpeg",
    "src": "/images/photos/IMG_8385.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8385.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 83,
    "filename": "IMG_8386.jpeg",
    "src": "/images/photos/IMG_8386.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8386.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 84,
    "filename": "IMG_8387.jpeg",
    "src": "/images/photos/IMG_8387.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8387.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 85,
    "filename": "IMG_8388.jpeg",
    "src": "/images/photos/IMG_8388.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8388.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 86,
    "filename": "IMG_8389.jpeg",
    "src": "/images/photos/IMG_8389.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8389.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 87,
    "filename": "IMG_8390.jpeg",
    "src": "/images/photos/IMG_8390.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8390.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 88,
    "filename": "IMG_8393.jpeg",
    "src": "/images/photos/IMG_8393.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8393.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 89,
    "filename": "IMG_8394.jpeg",
    "src": "/images/photos/IMG_8394.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8394.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 90,
    "filename": "IMG_8395.jpeg",
    "src": "/images/photos/IMG_8395.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8395.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 91,
    "filename": "IMG_8396.jpeg",
    "src": "/images/photos/IMG_8396.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8396.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 92,
    "filename": "IMG_8397.jpeg",
    "src": "/images/photos/IMG_8397.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8397.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 93,
    "filename": "IMG_8398.jpeg",
    "src": "/images/photos/IMG_8398.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8398.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 94,
    "filename": "IMG_8399.jpeg",
    "src": "/images/photos/IMG_8399.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8399.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 95,
    "filename": "IMG_8400.jpeg",
    "src": "/images/photos/IMG_8400.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8400.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 96,
    "filename": "IMG_8401.jpeg",
    "src": "/images/photos/IMG_8401.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8401.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 97,
    "filename": "IMG_8402.jpeg",
    "src": "/images/photos/IMG_8402.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8402.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 98,
    "filename": "IMG_8403.jpeg",
    "src": "/images/photos/IMG_8403.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8403.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 99,
    "filename": "IMG_8404.jpeg",
    "src": "/images/photos/IMG_8404.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8404.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 100,
    "filename": "IMG_8405.jpeg",
    "src": "/images/photos/IMG_8405.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8405.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 101,
    "filename": "IMG_8407.jpeg",
    "src": "/images/photos/IMG_8407.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8407.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 102,
    "filename": "IMG_8408.jpeg",
    "src": "/images/photos/IMG_8408.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8408.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 103,
    "filename": "IMG_8409.jpeg",
    "src": "/images/photos/IMG_8409.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8409.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 104,
    "filename": "IMG_8410.jpeg",
    "src": "/images/photos/IMG_8410.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8410.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 105,
    "filename": "IMG_8411.jpeg",
    "src": "/images/photos/IMG_8411.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8411.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 106,
    "filename": "IMG_8412.jpeg",
    "src": "/images/photos/IMG_8412.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8412.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 107,
    "filename": "IMG_8413.jpeg",
    "src": "/images/photos/IMG_8413.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8413.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 108,
    "filename": "IMG_8414.jpeg",
    "src": "/images/photos/IMG_8414.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8414.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 109,
    "filename": "IMG_8415.jpeg",
    "src": "/images/photos/IMG_8415.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8415.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 110,
    "filename": "IMG_8416.jpeg",
    "src": "/images/photos/IMG_8416.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8416.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 111,
    "filename": "IMG_8417.jpeg",
    "src": "/images/photos/IMG_8417.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8417.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 112,
    "filename": "IMG_8418.jpeg",
    "src": "/images/photos/IMG_8418.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8418.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 113,
    "filename": "IMG_8419.jpeg",
    "src": "/images/photos/IMG_8419.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8419.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 114,
    "filename": "IMG_8420.jpeg",
    "src": "/images/photos/IMG_8420.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8420.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 115,
    "filename": "IMG_8421.jpeg",
    "src": "/images/photos/IMG_8421.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8421.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 116,
    "filename": "IMG_8422.jpeg",
    "src": "/images/photos/IMG_8422.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8422.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 117,
    "filename": "IMG_8423.jpeg",
    "src": "/images/photos/IMG_8423.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8423.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 118,
    "filename": "IMG_8424.jpeg",
    "src": "/images/photos/IMG_8424.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8424.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 119,
    "filename": "IMG_8425.jpeg",
    "src": "/images/photos/IMG_8425.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8425.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 120,
    "filename": "IMG_8426.jpeg",
    "src": "/images/photos/IMG_8426.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8426.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 121,
    "filename": "IMG_8427.jpeg",
    "src": "/images/photos/IMG_8427.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8427.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 122,
    "filename": "IMG_8428.jpeg",
    "src": "/images/photos/IMG_8428.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8428.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 123,
    "filename": "IMG_8429.jpeg",
    "src": "/images/photos/IMG_8429.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8429.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 124,
    "filename": "IMG_8430.jpeg",
    "src": "/images/photos/IMG_8430.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8430.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 125,
    "filename": "IMG_8431.jpeg",
    "src": "/images/photos/IMG_8431.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8431.webp",
    "width": 3024,
    "height": 4032,
    "aspectRatio": 0.75
  },
  {
    "id": 126,
    "filename": "IMG_8432.jpeg",
    "src": "/images/photos/IMG_8432.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8432.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 127,
    "filename": "IMG_8435.jpeg",
    "src": "/images/photos/IMG_8435.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8435.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 128,
    "filename": "IMG_8436.jpeg",
    "src": "/images/photos/IMG_8436.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8436.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 129,
    "filename": "IMG_8437.jpeg",
    "src": "/images/photos/IMG_8437.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8437.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 130,
    "filename": "IMG_8438.jpeg",
    "src": "/images/photos/IMG_8438.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8438.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 131,
    "filename": "IMG_8439.jpeg",
    "src": "/images/photos/IMG_8439.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8439.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 132,
    "filename": "IMG_8440.jpeg",
    "src": "/images/photos/IMG_8440.jpeg",
    "thumb": "/images/photos_thumbs/IMG_8440.webp",
    "width": 4032,
    "height": 3024,
    "aspectRatio": 1.3333
  },
  {
    "id": 133,
    "filename": "f12fa40b-25f9-4670-a92a-e35a3d99fb79 2.jpg",
    "src": "/images/photos/f12fa40b-25f9-4670-a92a-e35a3d99fb79 2.jpg",
    "thumb": "/images/photos_thumbs/f12fa40b-25f9-4670-a92a-e35a3d99fb79 2.webp",
    "width": 3072,
    "height": 4080,
    "aspectRatio": 0.7529
  }
];
